### ISSUE TITLE
Bitfield invalid

### ISSUE THREAD

**Issue by DarkGD123** [GiorgioBrux/nitro-sniper-enhanced#54] opened 2021-02-21 11:47 UTC
Yeah 

`2021-02-21T11:35:26.347136+00:00 app[worker.1]:     at new Role (/app/node_modules/discord.js/src/structures/Role.js:28:20)
2021-02-21T11:35:26.347137+00:00 app[worker.1]:     at RoleManager.add (/app/node_modules/discord.js/src/managers/BaseManager.js:49:32)
2021-02-21T11:35:26.347137+00:00 app[worker.1]:     at RoleManager.add (/app/node_modules/discord.js/src/managers/RoleManager.js:30:18)
2021-02-21T11:35:26.347138+00:00 app[worker.1]:     at Message._patch (/app/node_modules/discord.js-light/classes.js:56:89)
2021-02-21T11:35:26.347138+00:00 app[worker.1]:     at new Message (/app/node_modules/discord.js/src/structures/Message.js:44:20)
2021-02-21T11:35:26.347139+00:00 app[worker.1]:     at new Message (/app/node_modules/discord.js-light/classes.js:11:4) {
2021-02-21T11:35:26.347140+00:00 app[worker.1]:   [Symbol(code)]: 'BITFIELD_INVALID'
2021-02-21T11:35:26.347140+00:00 app[worker.1]: }
2021-02-21T11:35:26.415042+00:00 heroku[worker.1]: Process exited with status 1
2021-02-21T11:35:26.531025+00:00 heroku[worker.1]: State changed from up to crashed`

**Comment by GiorgioBrux** [comment] 2021-02-21 14:28
@DarkGD123 Can you give me the env variables you are using (replacing the sensible parts with asterisks or similar)?

**Comment by quiet69** [comment] 2021-02-21 14:36
i'm getting the same issue
​https://quiet-sent.thigh.pics/emEC61411.png

**Comment by GiorgioBrux** [comment] 2021-02-21 14:57
Thanks @quiet69 , if anyone has the full error I would be really grateful because for some reason I can't reproduce it on my local installation.

**Comment by quiet69** [comment] 2021-02-21 15:29
@GiorgioBrux ​https://quiet-sent.thigh.pics/emf8B70Bd.png

**Comment by GiorgioBrux** [comment] 2021-02-21 16:07
It probably won't fix it, but can you try with the latest version (v.1.8.5) just to be sure?

**Comment by sonicm35** [comment] 2021-02-21 16:16
> It probably won't fix it, but can you try with the latest version (v.1.8.5) just to be sure?


```
/home/runner/GiorgioBrux-nitro-sniper-enhanced/node_modules/discord.js/src/util/BitField.js:151
    throw new RangeError('BITFIELD_INVALID', bit);
    ^

RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number: 0.
    at Function.resolve (/home/runner/GiorgioBrux-nitro-sniper-enhanced/node_modules/discord.js/src/util/BitField.js:151:11)
    at new BitField (/home/runner/GiorgioBrux-nitro-sniper-enhanced/node_modules/discord.js/src/util/BitField.js:17:38)
    at new Permissions (/home/runner/GiorgioBrux-nitro-sniper-enhanced/node_modules/discord.js/src/util/Permissions.js:11:1)
    at Role._patch (/home/runner/GiorgioBrux-nitro-sniper-enhanced/node_modules/discord.js/src/structures/Role.js:66:24)
    at new Role (/home/runner/GiorgioBrux-nitro-sniper-enhanced/node_modules/discord.js/src/structures/Role.js:28:20)
    at RoleManager.add (/home/runner/GiorgioBrux-nitro-sniper-enhanced/node_modules/discord.js/src/managers/BaseManager.js:49:32)
    at RoleManager.add (/home/runner/GiorgioBrux-nitro-sniper-enhanced/node_modules/discord.js/src/managers/RoleManager.js:30:18)
    at Message._patch (/home/runner/GiorgioBrux-nitro-sniper-enhanced/node_modules/discord.js-light/classes.js:89:89)
    at new Message (/home/runner/GiorgioBrux-nitro-sniper-enhanced/node_modules/discord.js/src/structures/Message.js:44:20)
    at new Message (/home/runner/GiorgioBrux-nitro-sniper-enhanced/node_modules/discord.js-light/classes.js:11:4) {
  [Symbol(code)]: 'BITFIELD_INVALID'
}
exit status 1
```
Same error with v1.8.5

**Comment by GiorgioBrux** [comment] 2021-02-21 17:58
Can someone try with 2bd5788044be6d0f8acc102cda31b026f4f7e00d? Sorry but again I still can't reproduce it so I'm a bit lost.

**Comment by quiet69** [comment] 2021-02-21 18:17
nope same issue... try these solutions maybe?
https://stackoverflow.com/questions/63441875/rangeerror-bitfield-invalid-when-checking-for-permission-overwrites-discord-j
https://stackoverflow.com/questions/63522829/rangeerror-bitfield-invalid-invalid-bitfield-flag-or-number

**Comment by GiorgioBrux** [comment] 2021-02-21 22:27
> nope same issue... try these solutions maybe?
> https://stackoverflow.com/questions/63441875/rangeerror-bitfield-invalid-when-checking-for-permission-overwrites-discord-j
> https://stackoverflow.com/questions/63522829/rangeerror-bitfield-invalid-invalid-bitfield-flag-or-number
> something concerning checking for permissions

Thanks for taking the time for doing some research but this is a likely problem with my fork of discord.js. I've reverted back the newest changes, can you check it again?

**Comment by DarkGD123** [comment] 2021-02-21 22:57
[Offtopic]

Can i use `attachment://` for the custom webhook avatar?

**Comment by GiorgioBrux** [comment] 2021-02-21 22:58
> [Offtopic]
> 
> Can i use `attachment://` for the custom webhook avatar?

No idea. Just upload to imgur and then use that url.

**Comment by DarkGD123** [comment] 2021-02-21 23:00
> > [Offtopic]
> > Can i use `attachment://` for the custom webhook avatar?
> 
> No idea. Just upload to imgur and then use that url.

Ah ok then, thanks

**Comment by GiorgioBrux** [comment] 2021-02-21 23:09
Anyway some people have told me it's fixed, so I'm closing this issue. If it still happens to anyone, send a message and I will reopen.

**Closed by GiorgioBrux** 2021-02-21 23:09 UTC
Labels: bug
