### ISSUE TITLE
webhook for redeemed nitro

### ISSUE THREAD

**Issue by IzukuMidoriyaPHP** [GiorgioBrux/nitro-sniper-enhanced#49] opened 2021-01-30 10:28 UTC
webhook for already redeemed nitros?

**Comment by IzukuMidoriyaPHP** [comment] 2021-01-30 10:36
like failed to redeem nitros i mean

**Comment by brams1441** [comment] 2021-01-30 22:37
I don think that will be useful, why would you need to know the codes that didnt work?

**Comment by GiorgioBrux** [comment] 2021-02-05 17:45
Unless I misunderstood, this is a duplicate of #29 so I'm closing.

**Closed by GiorgioBrux** 2021-02-05 17:45 UTC
